# Index and Slice 2-dim numpy array

In [1]:
import numpy as np
print(f'numpy version = {np.__version__}')

numpy version = 1.14.5


In [2]:
a=np.reshape(np.arange(1, 21), (4, 5))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [3]:
a[1]

array([ 6,  7,  8,  9, 10])

In [4]:
a[3]

array([16, 17, 18, 19, 20])

In [5]:
a[-1] # last row

array([16, 17, 18, 19, 20])

In [6]:
a[1,2]

8

In [7]:
a[1][2]

8

In [8]:
list(np.ndenumerate(a))

[((0, 0), 1),
 ((0, 1), 2),
 ((0, 2), 3),
 ((0, 3), 4),
 ((0, 4), 5),
 ((1, 0), 6),
 ((1, 1), 7),
 ((1, 2), 8),
 ((1, 3), 9),
 ((1, 4), 10),
 ((2, 0), 11),
 ((2, 1), 12),
 ((2, 2), 13),
 ((2, 3), 14),
 ((2, 4), 15),
 ((3, 0), 16),
 ((3, 1), 17),
 ((3, 2), 18),
 ((3, 3), 19),
 ((3, 4), 20)]

In [9]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# array[start:stop:step]

In [10]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
a[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [13]:
a[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
a[:, 2]

array([ 3,  8, 13, 18])

In [15]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
a[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [17]:
a[2:, :2]

array([[11, 12],
       [16, 17]])

In [18]:
a[:, 3:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20]])

In [19]:
a[:, 3:5]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20]])

In [20]:
a[:, -1]

array([ 5, 10, 15, 20])

In [21]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [22]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [23]:
a[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])