# shuffle and hsplit array

In [1]:
import numpy as np
print(f'numpy version = {np.__version__}')

numpy version = 1.14.5


In [2]:
a=np.arange(1, 33)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [3]:
np.random.shuffle(a) # inplace
a

array([30,  1,  5, 19, 21,  4, 22,  3, 20, 31, 26, 11,  6, 16,  8, 12, 28,
       24, 32,  9,  7,  2, 10, 13, 27, 17, 25, 15, 18, 29, 14, 23])

In [4]:
b=np.hsplit(a, 8)
b

[array([30,  1,  5, 19]),
 array([21,  4, 22,  3]),
 array([20, 31, 26, 11]),
 array([ 6, 16,  8, 12]),
 array([28, 24, 32,  9]),
 array([ 7,  2, 10, 13]),
 array([27, 17, 25, 15]),
 array([18, 29, 14, 23])]

In [5]:
b[0]

array([30,  1,  5, 19])

In [6]:
b[1]

array([21,  4, 22,  3])

### 2018 FIFA World Cup qualification

In [7]:
t=np.loadtxt('worldcup2018teams.txt',
             dtype='U', delimiter='\n')
t

array(['Russia', 'Brazil', 'Iran', 'Japan', 'Mexico', 'Belgium',
       'South Korea', 'Saudi Arabia', 'Germany', 'England', 'Spain',
       'Nigeria', 'Costa Rica', 'Poland', 'Egypt', 'Iceland', 'Serbia',
       'Portugal', 'France', 'Uruguay', 'Argentina', 'Colombia', 'Panama',
       'Senegal', 'Morocco', 'Tunisia', 'Switzerland', 'Croatia',
       'Sweden', 'Denmark', 'Australia', 'Peru'], dtype='<U12')

In [8]:
np.random.shuffle(t) # inplace shuffle
t

array(['Spain', 'Switzerland', 'Senegal', 'Mexico', 'England', 'Denmark',
       'Japan', 'Argentina', 'South Korea', 'Portugal', 'Brazil',
       'Tunisia', 'Australia', 'Saudi Arabia', 'Nigeria', 'Egypt', 'Peru',
       'Germany', 'Iceland', 'Iran', 'Uruguay', 'Serbia', 'Panama',
       'Costa Rica', 'Belgium', 'France', 'Russia', 'Croatia', 'Colombia',
       'Morocco', 'Sweden', 'Poland'], dtype='<U12')

In [9]:
grp=np.hsplit(t, 8) # split into 8 groups
grp

[array(['Spain', 'Switzerland', 'Senegal', 'Mexico'], dtype='<U12'),
 array(['England', 'Denmark', 'Japan', 'Argentina'], dtype='<U12'),
 array(['South Korea', 'Portugal', 'Brazil', 'Tunisia'], dtype='<U12'),
 array(['Australia', 'Saudi Arabia', 'Nigeria', 'Egypt'], dtype='<U12'),
 array(['Peru', 'Germany', 'Iceland', 'Iran'], dtype='<U12'),
 array(['Uruguay', 'Serbia', 'Panama', 'Costa Rica'], dtype='<U12'),
 array(['Belgium', 'France', 'Russia', 'Croatia'], dtype='<U12'),
 array(['Colombia', 'Morocco', 'Sweden', 'Poland'], dtype='<U12')]

In [10]:
grp[0]

array(['Spain', 'Switzerland', 'Senegal', 'Mexico'], dtype='<U12')

In [11]:
grp[1]

array(['England', 'Denmark', 'Japan', 'Argentina'], dtype='<U12')

In [12]:
for g in grp:
    print(g)

['Spain' 'Switzerland' 'Senegal' 'Mexico']
['England' 'Denmark' 'Japan' 'Argentina']
['South Korea' 'Portugal' 'Brazil' 'Tunisia']
['Australia' 'Saudi Arabia' 'Nigeria' 'Egypt']
['Peru' 'Germany' 'Iceland' 'Iran']
['Uruguay' 'Serbia' 'Panama' 'Costa Rica']
['Belgium' 'France' 'Russia' 'Croatia']
['Colombia' 'Morocco' 'Sweden' 'Poland']


In [13]:
for i, g in enumerate(grp):
    print(f'group {chr(65+i)}: {g}') # note chr(65) = 'A'

group A: ['Spain' 'Switzerland' 'Senegal' 'Mexico']
group B: ['England' 'Denmark' 'Japan' 'Argentina']
group C: ['South Korea' 'Portugal' 'Brazil' 'Tunisia']
group D: ['Australia' 'Saudi Arabia' 'Nigeria' 'Egypt']
group E: ['Peru' 'Germany' 'Iceland' 'Iran']
group F: ['Uruguay' 'Serbia' 'Panama' 'Costa Rica']
group G: ['Belgium' 'France' 'Russia' 'Croatia']
group H: ['Colombia' 'Morocco' 'Sweden' 'Poland']


In [14]:
np.random.choice(grp[1], size=2, replace=False) # randomly choose 2 teams from grp[1]

array(['Japan', 'Denmark'], dtype='<U12')

In [15]:
for g in grp: # choose 2 teams from each group
    print(np.random.choice(g, size=2, replace=False))

['Switzerland' 'Spain']
['Japan' 'Argentina']
['Tunisia' 'Brazil']
['Saudi Arabia' 'Australia']
['Iceland' 'Peru']
['Uruguay' 'Serbia']
['Croatia' 'France']
['Morocco' 'Poland']


In [16]:
for i, g in enumerate(grp):
    print(f'group {chr(65+i)}: {np.random.choice(g, size=2, replace=False)}')

group A: ['Mexico' 'Switzerland']
group B: ['Denmark' 'Argentina']
group C: ['Tunisia' 'South Korea']
group D: ['Egypt' 'Australia']
group E: ['Germany' 'Peru']
group F: ['Serbia' 'Costa Rica']
group G: ['Russia' 'Belgium']
group H: ['Sweden' 'Poland']
