In [1]:
import numpy as np
print(f'numpy version = {np.__version__}')

numpy version = 1.14.5


In [23]:
cf=np.array([-1000, 200, 500, 900])
rate=np.full(cf.size, .1)
# rate=np.array([0, .15, .17, .20])
period=np.arange(cf.size)

In [24]:
cf

array([-1000,   200,   500,   900])

In [25]:
rate

array([0.1, 0.1, 0.1, 0.1])

In [26]:
period

array([0, 1, 2, 3])

In [27]:
cf * 1/(1 + rate)**period

array([-1000.        ,   181.81818182,   413.2231405 ,   676.18332081])

In [28]:
npv=np.sum(cf * 1/(1 + rate)**period)
npv

271.22464312546924