In [1]:
import numpy as np
print(f'numpy version = {np.__version__}')

numpy version = 1.14.5


In [2]:
a=np.reshape(np.arange(1, 9), (4, 2))
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [3]:
b=np.reshape(np.arange(1, 9) * 20, (4, 2))
b

array([[ 20,  40],
       [ 60,  80],
       [100, 120],
       [140, 160]])

In [4]:
np.vstack((a, b))

array([[  1,   2],
       [  3,   4],
       [  5,   6],
       [  7,   8],
       [ 20,  40],
       [ 60,  80],
       [100, 120],
       [140, 160]])

In [5]:
c=np.reshape(np.arange(1, 9) * 11, (4, 2))
c

array([[11, 22],
       [33, 44],
       [55, 66],
       [77, 88]])

In [6]:
np.vstack((a, b, c))

array([[  1,   2],
       [  3,   4],
       [  5,   6],
       [  7,   8],
       [ 20,  40],
       [ 60,  80],
       [100, 120],
       [140, 160],
       [ 11,  22],
       [ 33,  44],
       [ 55,  66],
       [ 77,  88]])

In [7]:
np.hstack((a, b))

array([[  1,   2,  20,  40],
       [  3,   4,  60,  80],
       [  5,   6, 100, 120],
       [  7,   8, 140, 160]])

In [8]:
d=np.hstack((a, b, c))
d

array([[  1,   2,  20,  40,  11,  22],
       [  3,   4,  60,  80,  33,  44],
       [  5,   6, 100, 120,  55,  66],
       [  7,   8, 140, 160,  77,  88]])

In [9]:
e=np.hsplit(d, 3)

In [10]:
e[0]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
e[1]

array([[ 20,  40],
       [ 60,  80],
       [100, 120],
       [140, 160]])

In [12]:
e[2]

array([[11, 22],
       [33, 44],
       [55, 66],
       [77, 88]])

In [13]:
f=np.vsplit(d, 2)
f

[array([[ 1,  2, 20, 40, 11, 22],
        [ 3,  4, 60, 80, 33, 44]]), array([[  5,   6, 100, 120,  55,  66],
        [  7,   8, 140, 160,  77,  88]])]

In [14]:
f[0]

array([[ 1,  2, 20, 40, 11, 22],
       [ 3,  4, 60, 80, 33, 44]])

In [15]:
d

array([[  1,   2,  20,  40,  11,  22],
       [  3,   4,  60,  80,  33,  44],
       [  5,   6, 100, 120,  55,  66],
       [  7,   8, 140, 160,  77,  88]])

In [16]:
f[1]

array([[  5,   6, 100, 120,  55,  66],
       [  7,   8, 140, 160,  77,  88]])

## 1-dim

In [17]:
a=np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
b=np.arange(1, 11) * 50
b

array([ 50, 100, 150, 200, 250, 300, 350, 400, 450, 500])

In [19]:
np.hstack((a, b))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  50, 100, 150,
       200, 250, 300, 350, 400, 450, 500])

In [20]:
np.vstack((a, b))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]])

In [21]:
np.stack((a, b), axis=1)

array([[  1,  50],
       [  2, 100],
       [  3, 150],
       [  4, 200],
       [  5, 250],
       [  6, 300],
       [  7, 350],
       [  8, 400],
       [  9, 450],
       [ 10, 500]])