In [1]:
import numpy as np
print(f'numpy version = {np.__version__}')

numpy version = 1.14.5


#### การคำนวณตัวเลขตรวจสอบ (check digit) ของรหัสแท่งแบบ EAN-13
https://en.wikipedia.org/wiki/International_Article_Number#Calculation_of_checksum_digit

## method 1

In [2]:
ean13='400638133393x'

In [3]:
list(ean13[:12])

['4', '0', '0', '6', '3', '8', '1', '3', '3', '3', '9', '3']

In [4]:
a=np.array(list(ean13[:12]), dtype=int)
a

array([4, 0, 0, 6, 3, 8, 1, 3, 3, 3, 9, 3])

In [5]:
b=[1,3,1,3,1,3,1,3,1,3,1,3]
b

[1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3]

In [6]:
c=a*b
c

array([ 4,  0,  0, 18,  3, 24,  1,  9,  3,  9,  9,  9])

In [7]:
d=np.sum(c)
d

89

In [8]:
check_digit=0 if d % 10 == 0 else 10 - (d % 10)
check_digit

1

## method 2

In [9]:
ean13='400638133393x'

In [10]:
list(ean13[:12])

['4', '0', '0', '6', '3', '8', '1', '3', '3', '3', '9', '3']

In [11]:
a=np.array(list(ean13[:12]), dtype=int)
a

array([4, 0, 0, 6, 3, 8, 1, 3, 3, 3, 9, 3])

In [12]:
b=np.tile([1,3], 6)
b

array([1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3])

In [13]:
c=a*b
c

array([ 4,  0,  0, 18,  3, 24,  1,  9,  3,  9,  9,  9])

In [14]:
d=np.sum(c)
d

89

In [15]:
check_digit=0 if d % 10 == 0 else 10 - (d % 10)
check_digit

1

## method 3

In [16]:
def ean13_checkdigit(ean13):
    a=np.array(list(ean13[:12]), dtype=int)
    b=np.tile([1, 3], 6)
    d=np.sum(a * b)
    return 0 if d % 10 == 0 else 10 - (d % 10)

In [17]:
ean13_checkdigit('885018825110')

5

In [18]:
def ean13_checkdigit_v2(ean13):
    d=np.sum(np.array(list(ean13[:12]), dtype=int) * np.tile([1, 3], 6))
    return 0 if d % 10 == 0 else 10 - (d % 10)

In [19]:
ean13_checkdigit_v2('885018825110')

5

In [20]:
ean13_checkdigit_v2('400638133393x')

1