# Boolean array and Boolean indexing 

In [1]:
import numpy as np
print(f'NumPy version = {np.__version__}')
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format='retina'

NumPy version = 1.14.5


In [17]:
a=np.random.randint(0, 100, 20)
a

array([50, 32, 76, 91, 56, 73, 22, 25, 27, 21, 18, 16,  9, 59, 67, 43, 11,
       48, 98, 16])

In [18]:
a % 2 == 0

array([ True,  True,  True, False,  True, False,  True, False, False,
       False,  True,  True, False, False, False, False, False,  True,
        True,  True])

In [19]:
a[a % 2 == 0]

array([50, 32, 76, 56, 22, 18, 16, 48, 98, 16])

In [20]:
(a % 2 == 0) | (a % 3 == 0)

array([ True,  True,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True, False, False, False, False,  True,
        True,  True])

In [21]:
a[(a % 2 == 0) | (a % 3 == 0)]

array([50, 32, 76, 56, 22, 27, 21, 18, 16,  9, 48, 98, 16])

In [22]:
a[(a % 2 == 0) & (a % 3 == 0)]

array([18, 48])

In [25]:
np.where((a % 2 == 0) & (a % 3 == 0))

(array([10, 17]),)

## ตัวเลขที่ลงท้ายด้วย 9

In [6]:
p=np.random.randint(1, 9999, 100)
p

array([7411, 4046, 9791, 3262, 4535, 6274, 5863,  152, 8514, 2747, 2037,
       2513, 7077, 6966, 3719, 5980, 6319, 1488, 9488, 2019,  742, 8859,
       7947, 6098, 9066, 2421, 3841, 3803, 1586,  251, 4800, 5584, 3974,
       4332, 9598, 8032, 9852, 5370, 8998, 1179, 4447, 2749, 9739, 3223,
       1714, 9049, 8715, 7308, 3793,   18, 6503, 6564, 4896, 6496, 6627,
       7453, 9003, 3847, 3872, 6967, 8957, 8329, 6310, 3496, 5290, 3100,
       4142, 3806, 3907, 6175, 2726, 6760, 5169, 8761,   28, 9958, 3261,
       5993, 2388, 3342, 4331, 9327, 3534, 3842, 9704, 9130,  314,  647,
       2287, 1243, 7641, 4916, 8679, 9914, 3493, 5255, 1966, 9070, 9435,
       2020])

In [7]:
p % 10 == 9

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False,  True,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False])

In [8]:
p[p % 10 == 9]

array([3719, 6319, 2019, 8859, 1179, 2749, 9739, 9049, 8329, 5169, 8679])

## displ, cty, hwy

In [29]:
d=np.loadtxt('displ_cty_hwy.csv', delimiter=',')
d

array([[ 2.4, 21. , 31. ],
       [ 2.4, 22. , 31. ],
       [ 3.3, 18. , 27. ],
       [ 1.8, 28. , 37. ],
       [ 1.8, 26. , 35. ],
       [ 2.4, 21. , 31. ],
       [ 2.4, 21. , 31. ],
       [ 3.5, 19. , 28. ],
       [ 2.7, 17. , 22. ],
       [ 4. , 15. , 18. ],
       [ 4. , 16. , 20. ],
       [ 4. , 16. , 20. ],
       [ 4.7, 14. , 17. ],
       [ 5.7, 13. , 18. ]])

In [36]:
d == 28

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [37]:
(d == 28).astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
d[d == 28]

array([28., 28.])

In [34]:
np.where(d == 28)

(array([3, 7]), array([1, 2]))

In [10]:
d[:, 0] > 3

array([False, False,  True, False, False, False, False,  True, False,
        True,  True,  True,  True,  True])

In [11]:
d[d[:, 0] > 3]

array([[ 3.3, 18. , 27. ],
       [ 3.5, 19. , 28. ],
       [ 4. , 15. , 18. ],
       [ 4. , 16. , 20. ],
       [ 4. , 16. , 20. ],
       [ 4.7, 14. , 17. ],
       [ 5.7, 13. , 18. ]])

In [16]:
(d[:, 0] > 3) & (d[:, 1] > 15)

array([False, False,  True, False, False, False, False,  True, False,
       False,  True,  True, False, False])

In [15]:
d[(d[:, 0] > 3) & (d[:, 1] > 15)]

array([[ 3.3, 18. , 27. ],
       [ 3.5, 19. , 28. ],
       [ 4. , 16. , 20. ],
       [ 4. , 16. , 20. ]])