In [1]:
import numpy as np
print(f'Numpy version = {np.__version__}')

Numpy version = 1.14.5


In [2]:
a=np.array([24, 35, 18, 40])
a

array([24, 35, 18, 40])

In [3]:
age=[24, 35, 18, 40]
age

[24, 35, 18, 40]

In [4]:
b=np.array(age)
b

array([24, 35, 18, 40])

In [5]:
b.ndim

1

In [6]:
b.shape

(4,)

In [7]:
drink=np.array(['mocha', 'water', 'latte', 'espresso', 'coke'])
drink

array(['mocha', 'water', 'latte', 'espresso', 'coke'], dtype='<U8')

In [8]:
m=['water', 20, 'coffe', 50]
m

['water', 20, 'coffe', 50]

### สมาชิกทุกตัวใน numpy array ต้องเป็นข้อมูลประเภทเดียวกัน

In [9]:
m2=np.array(['water', 20, 'coffe', 50])
m2

array(['water', '20', 'coffe', '50'], dtype='<U5')

## 2-dim array

In [10]:
hw=np.array([[170, 167, 159], [70, 48, 50]])
hw

array([[170, 167, 159],
       [ 70,  48,  50]])

In [11]:
hw.shape

(2, 3)

In [12]:
hw.ndim

2

In [13]:
hw.size

6

### สร้าง matrix ขนาด 4 x 2 โดยให้สมาชิกทุกตัวมีค่าเป็น 0

In [14]:
z=np.zeros((4, 2))
z

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### สร้าง matrix ขนาด 5 x 3 โดยให้สมาชิกทุกตัวมีค่าเป็น 1

In [15]:
x=np.ones((5, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
k=np.zeros((4, 3))
k

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### กำหนดให้สมาชิกทุกตัวใน k มีค่าเป็น 9

In [17]:
k[:] = 9
k

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [18]:
e = np.identity(4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
e2 = np.eye(4) # เหมือนกับ np.identity()
e2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### การสร้าง numpy array ด้วย arange

In [20]:
f=np.arange(1, 11)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
f2=np.arange(1, 51)
f2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

### การปรับรูปร่างของ numpy array

In [22]:
f3=np.reshape(f2, (10, 5))
f3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [23]:
f4=np.reshape(np.arange(1, 51), (10, 5))
f4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

### การสร้าง numpy array ด้วย linspace

In [24]:
p=np.linspace(10, 100, 20)
p

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        28.94736842,  33.68421053,  38.42105263,  43.15789474,
        47.89473684,  52.63157895,  57.36842105,  62.10526316,
        66.84210526,  71.57894737,  76.31578947,  81.05263158,
        85.78947368,  90.52631579,  95.26315789, 100.        ])

### การอ่านข้อมูลในไฟล์มาเก็บเป็น numpy array

In [25]:
s=np.loadtxt('shoe_size.csv', 
             delimiter=',', 
             skiprows=1,
             usecols=(0, 2))
s

array([[34. ,  2. ],
       [34.5,  2.5],
       [35. ,  3. ],
       [35.5,  3.5],
       [36. ,  4. ],
       [36.5,  4. ],
       [37. ,  4.5],
       [37.5,  5. ],
       [38. ,  5.5],
       [38.5,  5.5],
       [39. ,  6. ],
       [39.5,  6.5],
       [40. ,  7. ],
       [40.5,  7.5],
       [41. ,  7.5],
       [41.5,  8. ],
       [42. ,  8.5],
       [42.5,  9. ],
       [43. ,  9.5],
       [43.5,  9.5],
       [44. , 10. ],
       [44.5, 10.5],
       [45. , 11. ],
       [45.5, 11.5],
       [46. , 11.5],
       [46.5, 12. ],
       [47. , 12.5],
       [47.5, 13. ],
       [48. , 13. ],
       [48.5, 13.5],
       [49. , 14. ],
       [49.5, 14.5],
       [50. , 15. ]])