# แก้สมการ 2 ตัวแปรด้วย matrix

In [1]:
import numpy as np
print(f'NumPy version = {np.__version__}')

NumPy version = 1.14.5


## โจทย์
มีเหรียญบาทและเหรียญ 5 อยู่ 90 เหรียญ  
x + y = 90  
จำนวนเงินรวม = 250  
x + 5y = 250  
ถามว่ามีเหรียญบาทและเหรียญห้ากี่เหรียญ

$$
x+y=90 \\
x+5y=250
$$

$$
\begin{bmatrix}
1 & 1 \\
1 & 5
\end{bmatrix}
\begin{bmatrix}
x \\
y
\end{bmatrix}
=
\begin{bmatrix}
90 \\
250
\end{bmatrix}
$$

$$
\begin{bmatrix}
1 & 1 \\
1 & 5
\end{bmatrix}
^{-1}
=
\begin{bmatrix}
1.25 & -0.25 \\
-0.25 & 0.25
\end{bmatrix}
$$

$$
\begin{bmatrix}
1.25 & -0.25 \\
-0.25 & 0.25
\end{bmatrix}
\begin{bmatrix}
90 \\
250
\end{bmatrix}
=
\begin{bmatrix}
50 \\
40
\end{bmatrix}
$$

In [2]:
a=np.array([[1, 1], [1,5]])
a

array([[1, 1],
       [1, 5]])

In [3]:
b=np.array([[90], [250]])
b

array([[ 90],
       [250]])

In [4]:
aI=np.linalg.inv(a) # linalg = linear algegra
aI

array([[ 1.25, -0.25],
       [-0.25,  0.25]])

In [5]:
aI * b # multiply element-wise

array([[112.5, -22.5],
       [-62.5,  62.5]])

In [6]:
-.25*90

-22.5

In [7]:
c=np.dot(aI, b) # multiply matrix aI and matrix b
c

array([[50.],
       [40.]])

In [8]:
np.dot(a, c)

array([[ 90.],
       [250.]])

In [9]:
c2=aI @ b # Python 3.5+
c2

array([[50.],
       [40.]])

## matrix

In [10]:
A=np.matrix([[1,1], [1,5]])
A

matrix([[1, 1],
        [1, 5]])

In [11]:
B=np.matrix([[90], [250]])
B

matrix([[ 90],
        [250]])

In [12]:
AI=A.I
AI

matrix([[ 1.25, -0.25],
        [-0.25,  0.25]])

In [13]:
C=AI * B
C

matrix([[50.],
        [40.]])

In [14]:
A.I * B

matrix([[50.],
        [40.]])

In [15]:
A*C

matrix([[ 90.],
        [250.]])