# Boolean array and Boolean indexing

In [1]:
import numpy as np
print(f'numpy version = {np.__version__}')

numpy version = 1.14.5


## Ex 1: 1-dim array

In [12]:
np.random.seed(10)
a=np.random.randint(0, 100, 20)
a

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0, 40, 36, 16, 11, 54, 88, 62,
       33, 72, 78])

In [3]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True,  True, False,
        True, False, False,  True,  True,  True, False, False, False,
       False, False])

In [4]:
a[a % 2 == 0]

array([ 8, 92, 82, 20, 22, 96,  0, 12, 18])

In [5]:
(a % 2 == 0) & (a > 50) # & (and)

array([False, False,  True, False,  True, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [6]:
np.where(a % 2 == 0)

(array([ 0,  2,  4,  6,  7,  9, 12, 13, 14]),)

In [8]:
a[np.where(a % 2 == 0)]

array([ 8, 92, 82, 20, 22, 96,  0, 12, 18])

## Ex 3: 2-dim array

In [14]:
d=np.loadtxt('station.txt', delimiter='\n', dtype='U')
d

array(['HUA', 'SAM', 'SIL', 'LUM', 'KHO', 'SIR', 'SUK', 'PET', 'RAM',
       'CUL', 'HUI', 'SUT', 'RAT', 'LAT', 'PHA', 'CHA', 'KAM', 'BAN'],
      dtype='<U3')

In [15]:
d == 'SIL'

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [16]:
d[np.where(d == 'SIL')]

array(['SIL'], dtype='<U3')

In [24]:
t1=np.random.choice(d, size=20, replace=True) #.resize(10, 2)
t1

array(['HUA', 'SIR', 'CUL', 'HUA', 'SUK', 'HUA', 'SIL', 'LUM', 'LUM',
       'LAT', 'SUT', 'KAM', 'LAT', 'SUT', 'BAN', 'SIR', 'SUT', 'SAM',
       'SUT', 'HUA'], dtype='<U3')

In [25]:
t2=np.random.choice(d, size=20, replace=True) #.resize(10, 2)
t2

array(['SIR', 'CUL', 'RAM', 'SIR', 'SUT', 'SUT', 'PET', 'RAM', 'RAM',
       'LAT', 'PHA', 'BAN', 'LAT', 'CUL', 'SAM', 'KHO', 'PET', 'PET',
       'CUL', 'PET'], dtype='<U3')

In [26]:
t=np.vstack((t1, t2)).T
t

array([['HUA', 'SIR'],
       ['SIR', 'CUL'],
       ['CUL', 'RAM'],
       ['HUA', 'SIR'],
       ['SUK', 'SUT'],
       ['HUA', 'SUT'],
       ['SIL', 'PET'],
       ['LUM', 'RAM'],
       ['LUM', 'RAM'],
       ['LAT', 'LAT'],
       ['SUT', 'PHA'],
       ['KAM', 'BAN'],
       ['LAT', 'LAT'],
       ['SUT', 'CUL'],
       ['BAN', 'SAM'],
       ['SIR', 'KHO'],
       ['SUT', 'PET'],
       ['SAM', 'PET'],
       ['SUT', 'CUL'],
       ['HUA', 'PET']], dtype='<U3')

In [27]:
d[np.where(d=='SAM')]

array(['SAM'], dtype='<U3')

In [35]:
i=np.where(d=='SAM')
i

(array([1]),)

In [43]:
type(i)

tuple

In [44]:
type(i[0])

numpy.ndarray

In [36]:
j=np.where(d=='SUK')
j

(array([6]),)

In [41]:
np.abs((i[0]-j[0])[0])

5

In [38]:
np.where(d=='SAM')[0] - np.where(d=='SUK')[0]

array([-5])

In [29]:
d[i]

array(['SAM'], dtype='<U3')

In [42]:
np.where(t1==t1)[0] - np.where(t2==t2)[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])