# Index and Slice array

In [1]:
import numpy as np
print(f'NumPy version = {np.__version__}')

NumPy version = 1.14.5


## 1-dim array

In [2]:
a = np.arange(10) * 10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
print(a.ndim)
print(a.size)

1
10


In [4]:
list(enumerate(a))

[(0, 0),
 (1, 10),
 (2, 20),
 (3, 30),
 (4, 40),
 (5, 50),
 (6, 60),
 (7, 70),
 (8, 80),
 (9, 90)]

In [5]:
for i, v in enumerate(a):
    print(i, v)

0 0
1 10
2 20
3 30
4 40
5 50
6 60
7 70
8 80
9 90


In [6]:
list(np.ndenumerate(a))

[((0,), 0),
 ((1,), 10),
 ((2,), 20),
 ((3,), 30),
 ((4,), 40),
 ((5,), 50),
 ((6,), 60),
 ((7,), 70),
 ((8,), 80),
 ((9,), 90)]

In [7]:
for i, v in np.ndenumerate(a):
    print(i, v)

(0,) 0
(1,) 10
(2,) 20
(3,) 30
(4,) 40
(5,) 50
(6,) 60
(7,) 70
(8,) 80
(9,) 90


In [8]:
a[2:]

array([20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
a[:3]

array([ 0, 10, 20])

In [10]:
a[-1]

90

In [11]:
a[4:]

array([40, 50, 60, 70, 80, 90])

In [12]:
a[2:5]

array([20, 30, 40])

In [13]:
a[::2]

array([ 0, 20, 40, 60, 80])

In [14]:
a[::3]

array([ 0, 30, 60, 90])

In [15]:
a[::-1] # reverse

array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0])

In [16]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
a[-3:] # last 3 elements

array([70, 80, 90])

In [18]:
a[-4:-1]

array([60, 70, 80])

## 2-dim array

In [19]:
b=np.reshape(np.arange(1, 21), (4, 5))
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
b[1, 2]

8

In [21]:
b[1][2]

8

In [22]:
list(np.ndenumerate(b))

[((0, 0), 1),
 ((0, 1), 2),
 ((0, 2), 3),
 ((0, 3), 4),
 ((0, 4), 5),
 ((1, 0), 6),
 ((1, 1), 7),
 ((1, 2), 8),
 ((1, 3), 9),
 ((1, 4), 10),
 ((2, 0), 11),
 ((2, 1), 12),
 ((2, 2), 13),
 ((2, 3), 14),
 ((2, 4), 15),
 ((3, 0), 16),
 ((3, 1), 17),
 ((3, 2), 18),
 ((3, 3), 19),
 ((3, 4), 20)]

In [23]:
for i, v in np.ndenumerate(b):
    print(i, v)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10
(2, 0) 11
(2, 1) 12
(2, 2) 13
(2, 3) 14
(2, 4) 15
(3, 0) 16
(3, 1) 17
(3, 2) 18
(3, 3) 19
(3, 4) 20


In [24]:
b[1]

array([ 6,  7,  8,  9, 10])

In [25]:
b[1, 2]

8

In [26]:
b[1, 3:]

array([ 9, 10])

In [27]:
b[:, 2]

array([ 3,  8, 13, 18])

In [28]:
b[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [29]:
b[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [30]:
b[:, ::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20]])

In [31]:
b[-1]

array([16, 17, 18, 19, 20])

## 3-dim array

In [32]:
c=np.reshape(np.arange(1, 31), (3, 2, 5))
c

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [33]:
for i, v in np.ndenumerate(c):
    print(i, v)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10
(1, 0, 0) 11
(1, 0, 1) 12
(1, 0, 2) 13
(1, 0, 3) 14
(1, 0, 4) 15
(1, 1, 0) 16
(1, 1, 1) 17
(1, 1, 2) 18
(1, 1, 3) 19
(1, 1, 4) 20
(2, 0, 0) 21
(2, 0, 1) 22
(2, 0, 2) 23
(2, 0, 3) 24
(2, 0, 4) 25
(2, 1, 0) 26
(2, 1, 1) 27
(2, 1, 2) 28
(2, 1, 3) 29
(2, 1, 4) 30


In [34]:
c[0]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
c[:, 1]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [26, 27, 28, 29, 30]])

In [36]:
c[0:2]

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [37]:
c[2]

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [38]:
c[-1]

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [39]:
c[:, :, 0]

array([[ 1,  6],
       [11, 16],
       [21, 26]])

In [40]:
c[:, :, 0].T

array([[ 1, 11, 21],
       [ 6, 16, 26]])

## shoe size
https://en.wikipedia.org/wiki/Shoe_size#Size_conversion

In [41]:
a = np.array(['EUR','Mondo','UK','US men','US women'])
a

array(['EUR', 'Mondo', 'UK', 'US men', 'US women'], dtype='<U8')

In [42]:
np.argwhere(a == 'UK')

array([[2]])

In [43]:
np.where(a == 'UK')

(array([2]),)

In [44]:
shoe_size = np.array([[34,215,2,3,4],[34.5,215,2.5,3.5,4.5],[35,220,3,4,5],[35.5,225,3.5,4.5,5.5],[36,225,4,5,6],[36.5,230,4,5,6],[37,235,4.5,5.5,6.5],[37.5,235,5,6,7],[38,240,5.5,6.5,7.5],[38.5,245,5.5,6.5,7.5],[39,245,6,7,8],[39.5,250,6.5,7.5,8.5],[40,255,7,8,9],[40.5,255,7.5,8.5,9.5],[41,260,7.5,8.5,9.5],[41.5,265,8,9,10],[42,265,8.5,9.5,10.5],[42.5,270,9,10,11],[43,275,9.5,10.5,11.5],[43.5,275,9.5,10.5,11.5],[44,280,10,11,12],[44.5,285,10.5,11.5,12.5],[45,285,11,12,13],[45.5,290,11.5,12.5,13.5],[46,295,11.5,12.5,13.5],[46.5,295,12,13,14],[47,300,12.5,13.5,14.5],[47.5,305,13,14,15],[48,305,13,14,15],[48.5,310,13.5,14.5,15.5],[49,315,14,15,16],[49.5,315,14.5,15.5,16.5],[50,320,15,16,17]])

In [45]:
shoe_size

array([[ 34. , 215. ,   2. ,   3. ,   4. ],
       [ 34.5, 215. ,   2.5,   3.5,   4.5],
       [ 35. , 220. ,   3. ,   4. ,   5. ],
       [ 35.5, 225. ,   3.5,   4.5,   5.5],
       [ 36. , 225. ,   4. ,   5. ,   6. ],
       [ 36.5, 230. ,   4. ,   5. ,   6. ],
       [ 37. , 235. ,   4.5,   5.5,   6.5],
       [ 37.5, 235. ,   5. ,   6. ,   7. ],
       [ 38. , 240. ,   5.5,   6.5,   7.5],
       [ 38.5, 245. ,   5.5,   6.5,   7.5],
       [ 39. , 245. ,   6. ,   7. ,   8. ],
       [ 39.5, 250. ,   6.5,   7.5,   8.5],
       [ 40. , 255. ,   7. ,   8. ,   9. ],
       [ 40.5, 255. ,   7.5,   8.5,   9.5],
       [ 41. , 260. ,   7.5,   8.5,   9.5],
       [ 41.5, 265. ,   8. ,   9. ,  10. ],
       [ 42. , 265. ,   8.5,   9.5,  10.5],
       [ 42.5, 270. ,   9. ,  10. ,  11. ],
       [ 43. , 275. ,   9.5,  10.5,  11.5],
       [ 43.5, 275. ,   9.5,  10.5,  11.5],
       [ 44. , 280. ,  10. ,  11. ,  12. ],
       [ 44.5, 285. ,  10.5,  11.5,  12.5],
       [ 45. , 285. ,  11. ,  12

In [46]:
shoe_size[2]

array([ 35., 220.,   3.,   4.,   5.])

In [47]:
shoe_size[:, 2]

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4. ,  4.5,  5. ,  5.5,  5.5,  6. ,
        6.5,  7. ,  7.5,  7.5,  8. ,  8.5,  9. ,  9.5,  9.5, 10. , 10.5,
       11. , 11.5, 11.5, 12. , 12.5, 13. , 13. , 13.5, 14. , 14.5, 15. ])

In [48]:
shoe_size[:, 0] == 41

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [49]:
shoe_size[shoe_size[:, 0] == 41]

array([[ 41. , 260. ,   7.5,   8.5,   9.5]])

In [50]:
shoe_size[:, 1:][shoe_size[:, 0] == 41]

array([[260. ,   7.5,   8.5,   9.5]])

In [51]:
shoe_size[:, 3][shoe_size[:, 0] == 41]

array([8.5])

In [52]:
shoe_size[:, 3][shoe_size[:, 0] == 41]

array([8.5])

In [53]:
a

array(['EUR', 'Mondo', 'UK', 'US men', 'US women'], dtype='<U8')

In [54]:
i, = np.where(a == 'UK')
i

array([2])

In [55]:
shoe_size[:, np.where(a == 'US men')][shoe_size[:, 0] == 41]

array([[[8.5]]])

In [56]:
a[2]

'UK'

In [57]:
a[i]

array(['UK'], dtype='<U8')

In [58]:
i, = np.where((a == 'UK') | (a == 'US men'))
i

array([2, 3])

In [59]:
shoe_size[:, np.where((a == 'UK') | (a == 'US men'))][shoe_size[:, 0] == 41]

array([[[7.5, 8.5]]])

## array of string

In [60]:
p = np.array(['Mercury', 'Venus', 'Earth', 
              'Mars', 'Jupiter', 'Saturn', 
              'Uranus', 'Neptune', 'Pluto'])
p

array(['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus',
       'Neptune', 'Pluto'], dtype='<U7')

In [61]:
p[2]

'Earth'