# descriptive statistics

In [1]:
import numpy as np
print(f'NumPy version = {np.__version__}')

NumPy version = 1.14.5


## 1-dim array

In [3]:
w = np.array([70, 48, 52, 60, 52])
w

array([70, 48, 52, 60, 52])

In [5]:
w.size # count

5

In [3]:
np.min(w)

48

In [4]:
np.max(w)

70

In [5]:
np.ptp(w) # max - min

22

In [7]:
np.sum(w)

282

In [8]:
np.mean(w)

56.4

In [9]:
np.median(w)

52.0

### use scipy.stats to calc mode

In [10]:
from scipy import stats

In [11]:
m=stats.mode(w)
m

ModeResult(mode=array([52]), count=array([2]))

In [12]:
m[0]

array([52])

In [13]:
m[0][0]

52

In [14]:
m[1]

array([2])

In [15]:
m[1][0]

2

In [6]:
np.var(w)

61.44000000000001

In [7]:
np.std(w)

7.8383671769061705

### sort

In [16]:
w1=np.sort(w) # ascending order
w1

array([48, 52, 52, 60, 70])

In [17]:
w2=np.sort(w)[::-1] # descending order
w2

array([70, 60, 52, 52, 48])

In [18]:
w

array([70, 48, 52, 60, 52])

In [19]:
w.sort() # inplace

In [20]:
w

array([48, 52, 52, 60, 70])

## 2 dim

In [21]:
b=np.reshape(np.arange(1, 21), (4, 5))
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [22]:
np.mean(b)

10.5

In [23]:
np.mean(b[0])

3.0

In [24]:
np.mean(b[:, 0])

8.5

In [25]:
np.mean(b, axis=1)

array([ 3.,  8., 13., 18.])

In [26]:
np.mean(b, axis=0)

array([ 8.5,  9.5, 10.5, 11.5, 12.5])

In [27]:
np.min(b)

1

In [28]:
np.min(b, axis=0)

array([1, 2, 3, 4, 5])

In [29]:
np.min(b, axis=1) # min in each row

array([ 1,  6, 11, 16])