# Index and Slice 1-dim Numpy array

In [1]:
import numpy as np
print(f'numpy version = {np.__version__}')

numpy version = 1.14.5


## 1-dim array

In [2]:
a=np.arange(10) * 10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
a[2]

20

In [4]:
a[5]

50

In [5]:
a[-1]

90

In [6]:
a[-2]

80

In [7]:
a[:3]

array([ 0, 10, 20])

In [8]:
a[0:3]

array([ 0, 10, 20])

In [9]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
a[3:]

array([30, 40, 50, 60, 70, 80, 90])

In [11]:
a[3:6]

array([30, 40, 50])

In [12]:
a[::2]

array([ 0, 20, 40, 60, 80])

In [13]:
a[1::2]

array([10, 30, 50, 70, 90])

In [14]:
a[-4:-1]

array([60, 70, 80])

In [15]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
a[::-1] # reverse array

array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0])

In [17]:
a[-3:] # last 3 elements

array([70, 80, 90])