# Boolean array and Boolean indexing

In [1]:
import numpy as np
print(f'numpy version = {np.__version__}')

numpy version = 1.14.5


## Ex 1: 1-dim array

In [2]:
a=np.random.randint(0, 100, 20)
a

array([71, 18,  2, 13, 69, 86, 57, 54, 44,  1, 50, 74, 35,  5, 37, 67, 78,
       85, 46, 27])

In [3]:
a % 2 == 0

array([False,  True,  True, False, False,  True, False,  True,  True,
       False,  True,  True, False, False, False, False,  True, False,
        True, False])

In [4]:
a[a % 2 == 0]

array([18,  2, 86, 54, 44, 50, 74, 78, 46])

In [5]:
(a % 2 == 0) & (a > 50) # & (and)

array([False, False, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False])

In [6]:
a[(a % 2 == 0) & (a > 50)]

array([86, 54, 74, 78])

In [7]:
(a % 2 == 0) | (a > 50) # | (or)

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True, False, False, False,  True,  True,  True,
        True, False])

In [8]:
a[(a % 2 == 0) | (a > 50)]

array([71, 18,  2, 69, 86, 57, 54, 44, 50, 74, 67, 78, 85, 46])

## Ex 2: 1-dim array

In [9]:
p=np.random.randint(1, 9999, 100)
p

array([8480, 6188, 2092, 7130, 7803, 7996, 6322, 4777, 2777, 3557, 9015,
       2441, 3178, 9254, 3052, 1837, 9195, 9489, 6318, 7979, 7195, 1117,
       8766, 7673, 9456,  301, 8452, 6256, 2650, 5549, 3298, 3500, 6392,
       9135,   54, 5334, 8766, 4312, 3627, 5705, 3765, 2924, 8412,  980,
       2115, 3104, 8088, 6053,  567, 6269, 7979,  688, 6459, 7204,  895,
       5452, 7776, 3034, 4356, 8011,  188, 1713,  109, 7124, 8076, 1801,
       5200, 8994, 4975, 9425, 5273, 5391, 3526, 5160, 7309,  234, 9856,
       2748, 5001,  168,   56,  294,  572, 9250, 3831, 5985,  624, 3441,
       5882, 1863, 5961, 2294, 3770, 3439, 4648, 6403, 9843, 2237, 5439,
       6063])

In [10]:
p % 10 == 9 # ตัวเลขที่ลงท้ายด้วย 9

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False,  True,
       False])

In [11]:
p[p % 10 == 9]

array([9489, 7979, 5549, 6269, 7979, 6459,  109, 7309, 3439, 5439])

### get index position

In [12]:
np.where(p % 10 == 9)

(array([17, 19, 29, 49, 50, 52, 62, 74, 93, 98]),)

In [13]:
p[np.where(p % 10 == 9)]

array([9489, 7979, 5549, 6269, 7979, 6459,  109, 7309, 3439, 5439])

## Ex 3: 2-dim array

In [14]:
d=np.loadtxt('displ_cty_hwy.csv', delimiter=',')
d

array([[ 2.4, 21. , 31. ],
       [ 2.4, 22. , 31. ],
       [ 3.3, 18. , 27. ],
       [ 1.8, 28. , 37. ],
       [ 1.8, 26. , 35. ],
       [ 2.4, 21. , 31. ],
       [ 2.4, 21. , 31. ],
       [ 3.5, 19. , 28. ],
       [ 2.7, 17. , 22. ],
       [ 4. , 15. , 18. ],
       [ 4. , 16. , 20. ],
       [ 4. , 16. , 20. ],
       [ 4.7, 14. , 17. ],
       [ 5.7, 13. , 18. ]])

In [15]:
d == 28

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [16]:
d[d == 28]

array([28., 28.])

In [19]:
d

array([[ 2.4, 21. , 31. ],
       [ 2.4, 22. , 31. ],
       [ 3.3, 18. , 27. ],
       [ 1.8, 28. , 37. ],
       [ 1.8, 26. , 35. ],
       [ 2.4, 21. , 31. ],
       [ 2.4, 21. , 31. ],
       [ 3.5, 19. , 28. ],
       [ 2.7, 17. , 22. ],
       [ 4. , 15. , 18. ],
       [ 4. , 16. , 20. ],
       [ 4. , 16. , 20. ],
       [ 4.7, 14. , 17. ],
       [ 5.7, 13. , 18. ]])

In [18]:
np.where(d == 28)

(array([3, 7]), array([1, 2]))

In [20]:
d[:, 0]

array([2.4, 2.4, 3.3, 1.8, 1.8, 2.4, 2.4, 3.5, 2.7, 4. , 4. , 4. , 4.7,
       5.7])

In [21]:
d[:, 0] > 3

array([False, False,  True, False, False, False, False,  True, False,
        True,  True,  True,  True,  True])

In [22]:
d[d[:, 0] > 3]

array([[ 3.3, 18. , 27. ],
       [ 3.5, 19. , 28. ],
       [ 4. , 15. , 18. ],
       [ 4. , 16. , 20. ],
       [ 4. , 16. , 20. ],
       [ 4.7, 14. , 17. ],
       [ 5.7, 13. , 18. ]])

In [23]:
d[(d[:, 0] > 3) & (d[:, 1] > 15)]

array([[ 3.3, 18. , 27. ],
       [ 3.5, 19. , 28. ],
       [ 4. , 16. , 20. ],
       [ 4. , 16. , 20. ]])