# Create ndarray

In [41]:
import numpy as np
print(f'NumPy version = {np.__version__}')

NumPy version = 1.14.4


In [2]:
a = np.array([5, 10, 100])
a

array([  5,  10, 100])

In [3]:
v = [170, 168, 155]

In [4]:
b = np.array(v)
b

array([170, 168, 155])

In [5]:
c = np.array([[4, 10, 25], [20, 47, 58]], dtype='float')
c

array([[ 4., 10., 25.],
       [20., 47., 58.]])

In [6]:
c.dtype

dtype('float64')

In [7]:
c.ndim

2

In [8]:
c.shape

(2, 3)

In [9]:
c.size

6

In [10]:
d = np.array(['tulip', 'jasmine', 'rose'])
d

array(['tulip', 'jasmine', 'rose'], dtype='<U7')

In [11]:
e = np.array(['coffee', 45, 'tea', 25])
e

array(['coffee', '45', 'tea', '25'], dtype='<U6')

In [12]:
f = np.array([['coffee', 'tea'], [45, 25]])
f

array([['coffee', 'tea'],
       ['45', '25']], dtype='<U6')

In [13]:
f.dtype

dtype('<U6')

In [14]:
f.ndim

2

In [15]:
f.size

4

In [16]:
f.shape

(2, 2)

In [17]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.ones((4, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
y = np.ones((4, 2))

In [20]:
y[:]=5
y

array([[5., 5.],
       [5., 5.],
       [5., 5.],
       [5., 5.]])

In [21]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
k = np.arange(1, 41)
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [24]:
k1 = np.reshape(k, (4, 10))
k1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [25]:
k1.ndim

2

In [26]:
k1.shape

(4, 10)

In [27]:
g = np.arange(10)
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
g1 = np.arange(1, 11, 1)
g1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
g1 = np.arange(1, 11, 2)
g1

array([1, 3, 5, 7, 9])

In [30]:
h = np.arange(5, 100, 10)
h

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [31]:
h1 = np.linspace(1, 20, 5)
h1

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [32]:
h2 = np.linspace(0, np.pi, 10)
h2

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [42]:
celsius = np.arange(101)
fahrenheit = celsius * 1.8 + 32
fahrenheit

array([ 32. ,  33.8,  35.6,  37.4,  39.2,  41. ,  42.8,  44.6,  46.4,
        48.2,  50. ,  51.8,  53.6,  55.4,  57.2,  59. ,  60.8,  62.6,
        64.4,  66.2,  68. ,  69.8,  71.6,  73.4,  75.2,  77. ,  78.8,
        80.6,  82.4,  84.2,  86. ,  87.8,  89.6,  91.4,  93.2,  95. ,
        96.8,  98.6, 100.4, 102.2, 104. , 105.8, 107.6, 109.4, 111.2,
       113. , 114.8, 116.6, 118.4, 120.2, 122. , 123.8, 125.6, 127.4,
       129.2, 131. , 132.8, 134.6, 136.4, 138.2, 140. , 141.8, 143.6,
       145.4, 147.2, 149. , 150.8, 152.6, 154.4, 156.2, 158. , 159.8,
       161.6, 163.4, 165.2, 167. , 168.8, 170.6, 172.4, 174.2, 176. ,
       177.8, 179.6, 181.4, 183.2, 185. , 186.8, 188.6, 190.4, 192.2,
       194. , 195.8, 197.6, 199.4, 201.2, 203. , 204.8, 206.6, 208.4,
       210.2, 212. ])

In [52]:
t = np.stack((celsius, fahrenheit), axis=1)
t

array([[  0. ,  32. ],
       [  1. ,  33.8],
       [  2. ,  35.6],
       [  3. ,  37.4],
       [  4. ,  39.2],
       [  5. ,  41. ],
       [  6. ,  42.8],
       [  7. ,  44.6],
       [  8. ,  46.4],
       [  9. ,  48.2],
       [ 10. ,  50. ],
       [ 11. ,  51.8],
       [ 12. ,  53.6],
       [ 13. ,  55.4],
       [ 14. ,  57.2],
       [ 15. ,  59. ],
       [ 16. ,  60.8],
       [ 17. ,  62.6],
       [ 18. ,  64.4],
       [ 19. ,  66.2],
       [ 20. ,  68. ],
       [ 21. ,  69.8],
       [ 22. ,  71.6],
       [ 23. ,  73.4],
       [ 24. ,  75.2],
       [ 25. ,  77. ],
       [ 26. ,  78.8],
       [ 27. ,  80.6],
       [ 28. ,  82.4],
       [ 29. ,  84.2],
       [ 30. ,  86. ],
       [ 31. ,  87.8],
       [ 32. ,  89.6],
       [ 33. ,  91.4],
       [ 34. ,  93.2],
       [ 35. ,  95. ],
       [ 36. ,  96.8],
       [ 37. ,  98.6],
       [ 38. , 100.4],
       [ 39. , 102.2],
       [ 40. , 104. ],
       [ 41. , 105.8],
       [ 42. , 107.6],
       [ 43

In [57]:
np.savetxt("temperature.csv", t, fmt='%.1f', delimiter=',', header='celsius,fahrenheit', comments='')

In [34]:
f = [c * 1.8 + 32 for c in range(101)]
f

[32.0,
 33.8,
 35.6,
 37.4,
 39.2,
 41.0,
 42.8,
 44.6,
 46.4,
 48.2,
 50.0,
 51.8,
 53.6,
 55.400000000000006,
 57.2,
 59.0,
 60.8,
 62.6,
 64.4,
 66.2,
 68.0,
 69.80000000000001,
 71.6,
 73.4,
 75.2,
 77.0,
 78.80000000000001,
 80.6,
 82.4,
 84.2,
 86.0,
 87.80000000000001,
 89.6,
 91.4,
 93.2,
 95.0,
 96.8,
 98.60000000000001,
 100.4,
 102.2,
 104.0,
 105.8,
 107.60000000000001,
 109.4,
 111.2,
 113.0,
 114.8,
 116.60000000000001,
 118.4,
 120.2,
 122.0,
 123.8,
 125.60000000000001,
 127.4,
 129.2,
 131.0,
 132.8,
 134.60000000000002,
 136.4,
 138.2,
 140.0,
 141.8,
 143.60000000000002,
 145.4,
 147.2,
 149.0,
 150.8,
 152.60000000000002,
 154.4,
 156.2,
 158.0,
 159.8,
 161.6,
 163.4,
 165.20000000000002,
 167.0,
 168.8,
 170.6,
 172.4,
 174.20000000000002,
 176.0,
 177.8,
 179.6,
 181.4,
 183.20000000000002,
 185.0,
 186.8,
 188.6,
 190.4,
 192.20000000000002,
 194.0,
 195.8,
 197.6,
 199.4,
 201.20000000000002,
 203.0,
 204.8,
 206.6,
 208.4,
 210.20000000000002,
 212.0]

In [35]:
%timeit -n5000 np.arange(101) * 1.8 + 32

6.69 µs ± 1.24 µs per loop (mean ± std. dev. of 7 runs, 5000 loops each)


In [36]:
%timeit -n5000 [c * 1.8 + 32 for c in range(101)]

9.98 µs ± 586 ns per loop (mean ± std. dev. of 7 runs, 5000 loops each)


### load data from text file into ndarray

## shoe size
https://en.wikipedia.org/wiki/Shoe_size#Size_conversion

In [38]:
s=np.loadtxt('shoe_size.csv', delimiter=',', skiprows=1, usecols=(0, 1, 3))
s

array([[ 34. , 215. ,   3. ],
       [ 34.5, 215. ,   3.5],
       [ 35. , 220. ,   4. ],
       [ 35.5, 225. ,   4.5],
       [ 36. , 225. ,   5. ],
       [ 36.5, 230. ,   5. ],
       [ 37. , 235. ,   5.5],
       [ 37.5, 235. ,   6. ],
       [ 38. , 240. ,   6.5],
       [ 38.5, 245. ,   6.5],
       [ 39. , 245. ,   7. ],
       [ 39.5, 250. ,   7.5],
       [ 40. , 255. ,   8. ],
       [ 40.5, 255. ,   8.5],
       [ 41. , 260. ,   8.5],
       [ 41.5, 265. ,   9. ],
       [ 42. , 265. ,   9.5],
       [ 42.5, 270. ,  10. ],
       [ 43. , 275. ,  10.5],
       [ 43.5, 275. ,  10.5],
       [ 44. , 280. ,  11. ],
       [ 44.5, 285. ,  11.5],
       [ 45. , 285. ,  12. ],
       [ 45.5, 290. ,  12.5],
       [ 46. , 295. ,  12.5],
       [ 46.5, 295. ,  13. ],
       [ 47. , 300. ,  13.5],
       [ 47.5, 305. ,  14. ],
       [ 48. , 305. ,  14. ],
       [ 48.5, 310. ,  14.5],
       [ 49. , 315. ,  15. ],
       [ 49.5, 315. ,  15.5],
       [ 50. , 320. ,  16. ]])