# basic aggregate function for ndarray

In [1]:
import numpy as np
print(f'numpy version = {np.__version__}')

numpy version = 1.14.5


## 1-dim array

In [2]:
w=np.array([70, 48, 52, 60, 52])
w

array([70, 48, 52, 60, 52])

In [3]:
w.size

5

In [4]:
np.min(w)

48

In [5]:
np.max(w)

70

In [6]:
np.sum(w)

282

In [7]:
np.mean(w)

56.4

In [8]:
np.median(w)

52.0

In [9]:
np.sort(w)

array([48, 52, 52, 60, 70])

## use scipy.stats to calculate mode

In [10]:
from scipy import stats

In [11]:
m=stats.mode(w)
m

ModeResult(mode=array([52]), count=array([2]))

In [12]:
m[0]

array([52])

In [13]:
m[0][0]

52

In [14]:
m[1]

array([2])

In [15]:
m[1][0]

2

In [16]:
np.sort(w)

array([48, 52, 52, 60, 70])

In [17]:
w

array([70, 48, 52, 60, 52])

In [18]:
w2=np.sort(w)[::-1]
w2

array([70, 60, 52, 52, 48])

In [19]:
w

array([70, 48, 52, 60, 52])

In [20]:
w.sort() #inplace

In [21]:
w

array([48, 52, 52, 60, 70])

## 2-dim array

In [22]:
a=np.reshape(np.arange(1, 21), (4, 5))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [23]:
np.mean(a)

10.5

In [24]:
a.size

20

In [25]:
a.shape

(4, 5)

In [26]:
np.mean(a[0])

3.0

In [27]:
np.mean(a[:, 1])

9.5

In [28]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [29]:
np.mean(a, axis=0)

array([ 8.5,  9.5, 10.5, 11.5, 12.5])

In [30]:
np.sum(a, axis=0)

array([34, 38, 42, 46, 50])

In [31]:
np.sum(a, axis=1)

array([15, 40, 65, 90])

In [32]:
np.std(a)

5.766281297335398

In [33]:
np.var(a)

33.25

In [34]:
np.ptp(a) # peak to peak

19

In [35]:
np.max(a) - np.min(a)

19