# Broadcasting เพื่อคำนวณอะเรย์ที่มีขนาดไม่เท่ากัน

In [1]:
import numpy as np
print(f'numpy version = {np.__version__}')

numpy version = 1.14.5


## scalar -> array

In [2]:
np.random.seed(9)
x=np.random.randint(1, 11, 5)
x

array([6, 7, 9, 7, 2])

In [3]:
x * 2

array([12, 14, 18, 14,  4])

In [4]:
b=np.array([2,2,2,2,2])

In [5]:
x * b

array([12, 14, 18, 14,  4])

In [6]:
x * np.array([2])

array([12, 14, 18, 14,  4])

In [7]:
np.repeat(np.array([2]), 5)

array([2, 2, 2, 2, 2])

In [8]:
x * np.repeat(np.array([2]), 5)

array([12, 14, 18, 14,  4])

## convert ndarray to z-score

In [9]:
mu=np.mean(x)
std=np.std(x)

In [10]:
mu

6.2

In [11]:
std

2.3151673805580453

In [12]:
z=(x - mu) / std
z

array([-0.08638684,  0.34554737,  1.2094158 ,  0.34554737, -1.81412369])

In [13]:
np.repeat(mu, 5)

array([6.2, 6.2, 6.2, 6.2, 6.2])

### scalar on 2-dim

In [14]:
a=np.arange(1, 7).reshape(3, -1) * 10
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [15]:
a.shape

(3, 2)

In [16]:
5 + a

array([[15, 25],
       [35, 45],
       [55, 65]])

In [17]:
np.array([5]) + a

array([[15, 25],
       [35, 45],
       [55, 65]])

In [18]:
# b=np.full((3, 2), 5)
b=np.full(a.shape, 5)
b

array([[5, 5],
       [5, 5],
       [5, 5]])

In [19]:
b + a

array([[15, 25],
       [35, 45],
       [55, 65]])

### broadcast 1-dim array to 2-dim array

In [20]:
c=np.array([2, 10])
c

array([ 2, 10])

In [21]:
a + c

array([[12, 30],
       [32, 50],
       [52, 70]])

In [22]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [23]:
print(a.shape)
print(c.shape)

(3, 2)
(2,)


In [24]:
a + c

array([[12, 30],
       [32, 50],
       [52, 70]])

In [25]:
# c จะถูกกระจายออกเป็น
np.tile(c, a.shape[0]).reshape(a.shape)

array([[ 2, 10],
       [ 2, 10],
       [ 2, 10]])

In [26]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [27]:
d=np.array([[2], [3], [4]])
d

array([[2],
       [3],
       [4]])

In [28]:
a + d

array([[12, 22],
       [33, 43],
       [54, 64]])

In [29]:
print(a.shape)
print(d.shape)

(3, 2)
(3, 1)


In [30]:
np.array([[2, 2], [3, 3], [4, 4]])

array([[2, 2],
       [3, 3],
       [4, 4]])

### ไม่สามารถทำการ broadcast ได้

In [31]:
e=np.array([[5], [100]])
e

array([[  5],
       [100]])

In [32]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [35]:
print(a.shape)
print(e.shape)

(3, 2)
(2, 1)


In [34]:
a + e

ValueError: operands could not be broadcast together with shapes (3,2) (2,1) 